# Generated by Django 4.2.5 on 2023-10-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_influencer', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user_created_at', models.DateTimeField(auto_now_add=True)),
                ('user_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'profile',
                'managed': True,
            },
        ),
    ]
