# Generated by Django 4.2.5 on 2023-10-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_profile_balance_profile_demonstration_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='demonstration_game',
            field=models.BooleanField(default=True),
        ),
    ]
