# Generated by Django 4.2.5 on 2023-10-10 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_remove_profile_demonstration_game_profile_ip_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='fake_value',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='afilliate_code',
        ),
    ]
