# Generated by Django 4.2.5 on 2023-10-10 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_remove_balance_fake_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='balance',
        ),
    ]
