# Generated by Django 4.2.5 on 2023-10-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_affiliate_personalized_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='code',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='personalized_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
