# Generated by Django 4.2.5 on 2023-10-10 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_profile_affiliate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposits',
            name='affiliate_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.affiliate'),
        ),
    ]
