# Generated by Django 4.2.5 on 2023-10-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_deposits_affiliate_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='configsApplication',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type_config', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('configsApplication_created_at', models.DateTimeField(auto_now_add=True)),
                ('configsApplication_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'configsApplication',
                'managed': True,
            },
        ),
        migrations.RenameField(
            model_name='affiliate',
            old_name='revshare',
            new_name='revshare_percent',
        ),
    ]
