# Generated by Django 4.2.5 on 2023-10-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_configsapplication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposits',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
