# Generated by Django 4.2.5 on 2023-10-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_alter_deposits_status_alter_withdraw_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
