# Generated by Django 4.2.5 on 2023-10-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0015_withdraw_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliate',
            old_name='affiliate_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='affiliate',
            old_name='affiliate_updated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='balance_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='balance_updated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='configsapplication',
            old_name='configsApplication_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='configsapplication',
            old_name='configsApplication_updated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='deposits',
            old_name='deposits_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='deposits',
            old_name='deposits_updated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_updated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='withdraw',
            old_name='withdraw_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='withdraw',
            old_name='withdraw_updated_at',
            new_name='updated_at',
        ),
    ]
