# Generated by Django 4.2.5 on 2023-10-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0016_rename_affiliate_created_at_affiliate_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bet_game',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='in_game',
            field=models.BooleanField(default=False),
        ),
    ]
