# Generated by Django 4.2.5 on 2023-10-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0018_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
