# Generated by Django 4.2.5 on 2023-10-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0019_game_is_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposits',
            name='external_id',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
