# Generated by Django 4.2.5 on 2023-10-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0020_deposits_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposits',
            name='pix_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
