# Generated by Django 4.2.5 on 2023-10-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0021_deposits_pix_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposits',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_code'),
        ),
    ]
