# Generated by Django 4.2.5 on 2023-10-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0025_alter_profile_cpf_alter_profile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='balance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='configsapplication',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deposits',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
