# Generated by Django 4.2.5 on 2023-10-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0026_alter_affiliate_id_alter_balance_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposits',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
