# Generated by Django 4.2.5 on 2023-10-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0027_alter_deposits_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='value_affiliate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
