# Generated by Django 4.2.5 on 2023-10-23 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0029_smsfunnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposits',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
