# Generated by Django 4.2.5 on 2023-10-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0031_alter_affiliate_created_at_alter_balance_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vanish',
            field=models.BooleanField(default=False),
        ),
    ]
