# Generated by Django 4.2.5 on 2023-10-24 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0033_affiliate_indication_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliate',
            name='indication_percent',
        ),
        migrations.RemoveField(
            model_name='affiliate',
            name='indication_total',
        ),
    ]
