# Generated by Django 4.2.5 on 2023-10-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0034_remove_affiliate_indication_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='indication_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='indication_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='cpa_percent',
            field=models.DecimalField(decimal_places=2, default=90.0, max_digits=10),
        ),
    ]
