# Generated by Django 4.1.13 on 2023-11-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0035_affiliate_indication_percent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='smsFunnel',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='personalized_username',
            new_name='utm',
        ),
        migrations.RemoveField(
            model_name='affiliate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='only_fake',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='deposits',
            name='affiliate_user',
        ),
        migrations.RemoveField(
            model_name='deposits',
            name='user',
        ),
        migrations.RemoveField(
            model_name='game',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='affiliate_user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bet_game',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='user',
        ),
        migrations.AddField(
            model_name='affiliate',
            name='cpa_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='cpa_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='cpa_last_month',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='cpa_month',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='indication_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='reveshare_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='reveshare_last_month',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='reveshare_month',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='total_earnings_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='total_earnings_last_month',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='total_earnings_month',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='balance',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='balance',
            name='last_deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='balance',
            name='last_deposit_bigger',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='deposits',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='affiliate_email',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_deposit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='qt_deposit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='qt_withdraw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
