# Generated by Django 4.1.13 on 2023-11-16 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0036_delete_smsfunnel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ggr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ggr',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ggr_history',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(default='', max_length=255)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ggr_history',
                'managed': True,
            },
        ),
    ]
