# Generated by Django 4.1.13 on 2023-11-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0037_ggr_ggr_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliate',
            old_name='reveshare_day',
            new_name='revshare_day',
        ),
        migrations.RenameField(
            model_name='affiliate',
            old_name='reveshare_last_month',
            new_name='revshare_last_month',
        ),
        migrations.RenameField(
            model_name='affiliate',
            old_name='reveshare_month',
            new_name='revshare_month',
        ),
    ]
