# Generated by Django 4.2.5 on 2023-11-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0038_rename_reveshare_day_affiliate_revshare_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='cpa_percent',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='revshare_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
