# Generated by Django 4.2.5 on 2023-11-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0039_alter_affiliate_cpa_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='value_ggr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='balance',
            name='value_original',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ggr_history',
            name='external_id',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='ggr_history',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='ggr_history',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='cpa_percent',
            field=models.DecimalField(decimal_places=2, default=16.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='revshare_percent',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=10),
        ),
    ]
