# Generated by Django 4.1.13 on 2023-11-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0040_balance_value_ggr_balance_value_original_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='game_test',
            field=models.IntegerField(default=3),
        ),
    ]
