# Generated by Django 4.1.13 on 2023-11-29 05:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0041_profile_game_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='dashboards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type_dashboard', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dashboards',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='withdraw_free',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(default='', max_length=255)),
                ('ip', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'withdraw_free',
                'managed': True,
            },
        ),
    ]
