# Generated by Django 4.1.13 on 2023-11-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0042_dashboards_withdraw_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboards',
            name='forced_data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
