# Generated by Django 4.1.13 on 2023-11-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0043_dashboards_forced_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboards',
            old_name='forced_data',
            new_name='forced_date',
        ),
    ]
